# Generated by Django 4.0.4 on 2022-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('second_title', models.CharField(max_length=100)),
                ('icon', models.FileField(null=True, upload_to='images/home/icons')),
                ('image', models.FileField(null=True, upload_to='images/home')),
                ('allowing', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
    ]
