# Generated by Django 4.0.4 on 2022-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_rename_homeoptions_homeoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
