# Generated by Django 4.0.4 on 2022-07-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_alter_sidebar_title_alter_sidebar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('tips', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
