# Generated by Django 4.0.4 on 2022-07-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_homeoption_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeoption',
            options={'ordering': ('-created_time',)},
        ),
    ]
