# Generated by Django 4.0.4 on 2022-07-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_homeoption_show_in_slider_alter_homeoption_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeoption',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
