# Generated by Django 4.0.4 on 2022-07-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_alter_homeoption_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeoption',
            old_name='allowing',
            new_name='show_in_page',
        ),
    ]
