# Generated by Django 4.0.4 on 2022-04-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
