# Generated by Django 4.0.4 on 2022-06-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_remove_contactinfo_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
