# Generated by Django 4.0.4 on 2022-06-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0004_opinion_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
