# Generated by Django 4.0.4 on 2022-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0005_contactinfo_second_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='street_address',
            field=models.CharField(max_length=1500),
        ),
    ]
