# Generated by Django 4.0.4 on 2022-06-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0006_alter_contactinfo_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='street_address',
            field=models.TextField(max_length=1500),
        ),
    ]
