# Generated by Django 4.0.4 on 2022-06-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0007_alter_contactinfo_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='google_map_url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
