# Generated by Django 4.0.4 on 2022-06-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0008_contactinfo_google_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='message',
            field=models.TextField(max_length=150),
        ),
    ]
