# Generated by Django 4.0.4 on 2022-04-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0003_service_allowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
