# Generated by Django 4.0.4 on 2022-05-18 20:24

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=600)),
                ('visits', models.IntegerField(blank=True, default=1)),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='images/article')),
                ('video', models.FileField(null=True, upload_to='videos/article')),
                ('allowing', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
