# Generated by Django 4.0.4 on 2022-06-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0005_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='visits',
        ),
    ]
