# Generated by Django 4.0.4 on 2022-07-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0010_alter_article_options_alter_article_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_time',)},
        ),
    ]
