# Generated by Django 4.0.4 on 2022-06-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('first_division', models.BooleanField(default=False)),
                ('second_division', models.BooleanField(default=False)),
                ('third_division', models.BooleanField(default=False)),
                ('allowing', models.BooleanField(default=False)),
            ],
        ),
    ]
