# Generated by Django 4.0.4 on 2022-07-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_alter_aboutus_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/about')),
                ('allowing', models.BooleanField(default=False)),
            ],
        ),
    ]
